model_dir: run/

data:
  train_features_file: {data_dir}/train.tfrecord
  train_labels_file: {data_dir}/train.labels
  eval_features_file: {data_dir}/validation.tfrecord
  eval_labels_file: {data_dir}/validation.labels
  labels_vocabulary: labels.txt
  config_file: {data_dir}/header.txt

params:
  optimizer: AdamOptimizer
  learning_rate: 0.001

train:
  batch_size: 128
  save_checkpoints_steps: 200
  train_steps: 2000
  sample_buffer_size: 5000

eval:
  eval_delay: 10
  exporters:
    - best